depth_anything:
  ros__parameters:
    # Model configuration
    model_file : ''
    encoder: vitb
    device : 'cuda:0'
    # ROS topic configuration
    image_topic: /image_raw
    depth_image_topic : /depth
